### ISSUE TITLE
Service is timing out

### ISSUE THREAD

**Issue by bcardarella** [kura/blackhole#5]
I'm making a simple request with Ruby:

```ruby
> msgstr = <<END_OF_MESSAGE
 From: Your Name <your@mail.address>
 To: Destination Address <someone@example.com>
 Subject: test message
 Date: Sat, 23 Jun 2001 16:26:43 +0900
 Message-Id: <unique.message.id.string@example.com>

 This is a test message.
 END_OF_MESSAGE
=> "From: Your Name <your@mail.address>\nTo: Destination Address <someone@example.com>\nSubject: test message\nDate: Sat, 23 Jun 2001 16:26:43 +0900\nMessage-Id: <unique.message.id.string@example.com>\n\nThis is a test message.\n"

> require 'net/smtp'
=> true

> Net::SMTP.start("blackhole.io", 25) do |smtp|
   smtp.send_message(msgstr, "from@example.com", ["to@example.com"])
 end

Net::OpenTimeout: execution expired
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/smtp.rb:551:in `block in do_start'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `call'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
        from /Users/bcardarella/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/smtp.rb:457:in `start'
        from (irb):11
        from /Users/bcardarella/.rbenv/versions/2.2.4/bin/irb:11:in `<main>'
```

Ruby's SMTP api seems similar to Python's, but I am getting a timeout error. Are there any known issues with the service at the moment?

**Comment by bcardarella** [comment]
fwiw I am also timing out with `telnet blackhole.io 25`

**Comment by kura** [comment]
Everything should be ok now, sorry for the late reply. There's been a lot of activity on the platform lately.
